xcopy /s /y ".\Client\*.hlsl" ".\x64\Debug"
xcopy /s /y ".\Client\*.hlsl" ".\x64\Release"
xcopy /s /y ".\Client\*.hlsli" ".\x64\Debug"
xcopy /s /y ".\Client\*.hlsli" ".\x64\Release"
xcopy /s /y /i ".\External\Common\Data\*.json" ".\x64\Debug\Data"
xcopy /s /y /i ".\External\Common\Data\*.json" ".\x64\Release\Data"
xcopy /s /e /y ".\Modeling" ".\x64\Modeling\"
xcopy /s /e /y ".\Resource" ".\x64\Resource\"
xcopy /s /y ".\Resource\Sound\lib\fmodL.dll" ".\x64\Debug"
xcopy /s /y ".\Resource\Sound\lib\fmod.dll" ".\x64\Release"