xcopy /s /y ".\Client\*.hlsl" ".\x64\Debug"
xcopy /s /y ".\Client\*.hlsl" ".\x64\Release"
xcopy /s /y /i ".\Client\Data\*.json" ".\x64\Debug\Data"
xcopy /s /y /i ".\Client\Data\*.json" ".\x64\Release\Data"
xcopy /s /e /y ".\Modeling" ".\x64\Modeling\"